# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Steampipe < Formula
  desc "select * from cloud;"
  homepage "https://steampipe.io"
  version "0.15.1-dev.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/turbot/steampipe/releases/download/v0.15.1-dev.0/steampipe_darwin_arm64.zip"
      sha256 "9ea4e56e1dd171ec92d9fb931cc40d02c7fe58babf135dc2f14a980ef11a6ef6"

      def install
        bin.install "steampipe"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/turbot/steampipe/releases/download/v0.15.1-dev.0/steampipe_darwin_amd64.zip"
      sha256 "98066866bdb1a2b0d511c94baf4bfdd70801b2dfd9795610da19e3f1b06919d6"

      def install
        bin.install "steampipe"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/turbot/steampipe/releases/download/v0.15.1-dev.0/steampipe_linux_arm64.tar.gz"
      sha256 "2902f0647e60fcbafe4c6dd478d3cda3cd9e8b96b0e2ffbb41e792cd91045910"

      def install
        bin.install "steampipe"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/turbot/steampipe/releases/download/v0.15.1-dev.0/steampipe_linux_amd64.tar.gz"
      sha256 "307e3b0d21a7db0f65aec3cc237dc082b9cba92f1890e7f0a25e411d4397a790"

      def install
        bin.install "steampipe"
      end
    end
  end
end
