# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FlowpipeAT061 < Formula
  desc "Flowpipe is a cloud scripting engine. Automation and workflow to connect your clouds to the people, systems and data that matters."
  homepage "https://flowpipe.io/"
  version "0.6.1"

  on_macos do
    on_intel do
      url "https://github.com/turbot/flowpipe/releases/download/v0.6.1/flowpipe.darwin.amd64.tar.gz"
      sha256 "5e46ccf5f3318db76439e4e640904fca424343e628e913f15e3ad9cab8768f5a"

      def install
        bin.install "flowpipe"
      end
    end
    on_arm do
      url "https://github.com/turbot/flowpipe/releases/download/v0.6.1/flowpipe.darwin.arm64.tar.gz"
      sha256 "c970c255e4f10b7b79425de19c932bb6c2cdffd942054db5224c1e37aac0fb9f"

      def install
        bin.install "flowpipe"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/turbot/flowpipe/releases/download/v0.6.1/flowpipe.linux.amd64.tar.gz"
        sha256 "22c1fc5ef7e2157fb6df848306f39e3c13c9f58cf5a2b1d6d2aec43310c1621e"

        def install
          bin.install "flowpipe"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/turbot/flowpipe/releases/download/v0.6.1/flowpipe.linux.arm64.tar.gz"
        sha256 "04497cbf2ec3334ea04fa001aaa3f03e0a8a6a9faa3edd1499a83ee82a8df40e"

        def install
          bin.install "flowpipe"
        end
      end
    end
  end
end
