# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FlowpipeAT011 < Formula
  desc "Flowpipe is a cloud scripting engine. Automation and workflow to connect your clouds to the people, systems and data that matters."
  homepage "https://flowpipe.io/"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/turbot/flowpipe/releases/download/v0.1.1/flowpipe.darwin.arm64.tar.gz"
      sha256 "26fc85d9eb5c1fdaf9704cdd7c5d25d7730643b9a6cab3b1f0e569c1880e88b4"

      def install
        bin.install "flowpipe"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/turbot/flowpipe/releases/download/v0.1.1/flowpipe.darwin.amd64.tar.gz"
      sha256 "f4f9d1bf01a8d6fb80480f58ccf3239274043871f80e25226f55f73c906430d4"

      def install
        bin.install "flowpipe"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/turbot/flowpipe/releases/download/v0.1.1/flowpipe.linux.arm64.tar.gz"
      sha256 "767988f19fdef9f7c68d5a380046132a2c9efe2d6da68a022ec79afa2460e026"

      def install
        bin.install "flowpipe"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/turbot/flowpipe/releases/download/v0.1.1/flowpipe.linux.amd64.tar.gz"
      sha256 "0a45e8aeb835cb11ec8b5aef4c2f6c8793ed8a4b96219e4a1c1e3e33ac8c27ba"

      def install
        bin.install "flowpipe"
      end
    end
  end
end
