# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FlowpipeAT010 < Formula
  desc "Flowpipe is a cloud scripting engine. Automation and workflow to connect your clouds to the people, systems and data that matters."
  homepage "https://flowpipe.io/"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/turbot/flowpipe/releases/download/v0.1.0/flowpipe.darwin.arm64.tar.gz"
      sha256 "f4dcaa3c02fb0870715144d160f76140fa320431b5e9977cc95c064b3d2aa6f5"

      def install
        bin.install "flowpipe"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/turbot/flowpipe/releases/download/v0.1.0/flowpipe.darwin.amd64.tar.gz"
      sha256 "1c583675ef2a9515a7e07af8f25130d58b3f4ba615fa9950a2b3cce4bc8e893f"

      def install
        bin.install "flowpipe"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/turbot/flowpipe/releases/download/v0.1.0/flowpipe.linux.arm64.tar.gz"
      sha256 "e9457b6f8861fdad47e33ea3e38cbbe5b9fa995377262add9be67bbbb0b2082c"

      def install
        bin.install "flowpipe"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/turbot/flowpipe/releases/download/v0.1.0/flowpipe.linux.amd64.tar.gz"
      sha256 "444c8338be0b1738cec9bc5b07cbf4a4e652062da0a0589634fdfd30f43afe8c"

      def install
        bin.install "flowpipe"
      end
    end
  end
end
