# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FlowpipeAT030 < Formula
  desc "Flowpipe is a cloud scripting engine. Automation and workflow to connect your clouds to the people, systems and data that matters."
  homepage "https://flowpipe.io/"
  version "0.3.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/turbot/flowpipe/releases/download/v0.3.0/flowpipe.darwin.arm64.tar.gz"
      sha256 "1e334eb811df1ca084db8e0489171a18bd7248fb595e6631f324c3e20009b428"

      def install
        bin.install "flowpipe"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/turbot/flowpipe/releases/download/v0.3.0/flowpipe.darwin.amd64.tar.gz"
      sha256 "e1c009e679ed2c75a4a9d9e551e8a243fc0fa4fd6800fdee2948575f953de21c"

      def install
        bin.install "flowpipe"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/turbot/flowpipe/releases/download/v0.3.0/flowpipe.linux.arm64.tar.gz"
      sha256 "d02a5963383b0a8d3a3fc01c9e97fceb90214d46c85a4495d250546f8a717f44"

      def install
        bin.install "flowpipe"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/turbot/flowpipe/releases/download/v0.3.0/flowpipe.linux.amd64.tar.gz"
      sha256 "09a8f22cabad1c6b979a219196010e555e7b9cc245ebe3024d2f947b29678f15"

      def install
        bin.install "flowpipe"
      end
    end
  end
end
