# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FlowpipeAT011 < Formula
  desc "Flowpipe is a cloud scripting engine. Automation and workflow to connect your clouds to the people, systems and data that matters."
  homepage "https://flowpipe.io/"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/turbot/flowpipe/releases/download/v0.1.1/flowpipe.darwin.arm64.tar.gz"
      sha256 "f6ddaf77f45a267f5b779d0fa50337c527cdec69acd18fe259f000422651eff2"

      def install
        bin.install "flowpipe"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/turbot/flowpipe/releases/download/v0.1.1/flowpipe.darwin.amd64.tar.gz"
      sha256 "eee0e335daf51c4ec6d0479ce848b002957f2a53da94df4db8cd852814b444b1"

      def install
        bin.install "flowpipe"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/turbot/flowpipe/releases/download/v0.1.1/flowpipe.linux.arm64.tar.gz"
      sha256 "b5695d49e9b60934bd53b16bd1d1a981ca9622f9fa92bcc855018af6118665a1"

      def install
        bin.install "flowpipe"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/turbot/flowpipe/releases/download/v0.1.1/flowpipe.linux.amd64.tar.gz"
      sha256 "84858bd2771e6421a4c65fa5a83160929796cc2facc3839e6911a0bc8aa73dae"

      def install
        bin.install "flowpipe"
      end
    end
  end
end
