# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FlowpipeAT091 < Formula
  desc "Flowpipe is a cloud scripting engine. Automation and workflow to connect your clouds to the people, systems and data that matters."
  homepage "https://flowpipe.io/"
  version "0.9.1"

  on_macos do
    on_intel do
      url "https://github.com/turbot/flowpipe/releases/download/v0.9.1/flowpipe.darwin.amd64.tar.gz"
      sha256 "417a863f35cfbb75bdd653c5f841d35bc9685a43e3acd4173d43db0dbc7fce9c"

      def install
        bin.install "flowpipe"
      end
    end
    on_arm do
      url "https://github.com/turbot/flowpipe/releases/download/v0.9.1/flowpipe.darwin.arm64.tar.gz"
      sha256 "df47f2f2a1beecd7eee81bc6a9e4950a4e7fdbc1f00211e3352c0cf1629062c1"

      def install
        bin.install "flowpipe"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/turbot/flowpipe/releases/download/v0.9.1/flowpipe.linux.amd64.tar.gz"
        sha256 "773659aa1d44b2bf25e944874d37e36f11d450c4032a60befda904315e2b9115"

        def install
          bin.install "flowpipe"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/turbot/flowpipe/releases/download/v0.9.1/flowpipe.linux.arm64.tar.gz"
        sha256 "169e77d83f27e2931116c6b5f03c627f39d422f5435a9dff00e2eb98212944a9"

        def install
          bin.install "flowpipe"
        end
      end
    end
  end
end
