# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FlowpipeAT080 < Formula
  desc "Flowpipe is a cloud scripting engine. Automation and workflow to connect your clouds to the people, systems and data that matters."
  homepage "https://flowpipe.io/"
  version "0.8.0"

  on_macos do
    on_intel do
      url "https://github.com/turbot/flowpipe/releases/download/v0.8.0/flowpipe.darwin.amd64.tar.gz"
      sha256 "9185ae1a89ca655bcbceba29795e0a8c0e5adaadfb3f6e23845f9468c4b17c3a"

      def install
        bin.install "flowpipe"
      end
    end
    on_arm do
      url "https://github.com/turbot/flowpipe/releases/download/v0.8.0/flowpipe.darwin.arm64.tar.gz"
      sha256 "94659f79af9a1dcc0e8113930e80a6467818c367f082c477ed0f239d0d4646b9"

      def install
        bin.install "flowpipe"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/turbot/flowpipe/releases/download/v0.8.0/flowpipe.linux.amd64.tar.gz"
        sha256 "efb3199fabb45e776a7e4c44a76d34d615d9fbd40a5081844c07cc2f9433d1c1"

        def install
          bin.install "flowpipe"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/turbot/flowpipe/releases/download/v0.8.0/flowpipe.linux.arm64.tar.gz"
        sha256 "ae197744b6ee30ef6c174791f2695bed219c08e3500968e20fd00067b81e5ac5"

        def install
          bin.install "flowpipe"
        end
      end
    end
  end
end
