# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FlowpipeAT010 < Formula
  desc "Flowpipe is a cloud scripting engine. Automation and workflow to connect your clouds to the people, systems and data that matters."
  homepage "https://flowpipe.io/"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/turbot/flowpipe/releases/download/v0.1.0/flowpipe.darwin.arm64.tar.gz"
      sha256 "c5fcbac353ed5b2dec306c86b87d24a9987b8d7626f4b01bbdaac64b85565b15"

      def install
        bin.install "flowpipe"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/turbot/flowpipe/releases/download/v0.1.0/flowpipe.darwin.amd64.tar.gz"
      sha256 "e11dda03a49dd0ced3136c95e10e2194c20d5da1ebe3fcef5a5d1e10bf87e51a"

      def install
        bin.install "flowpipe"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/turbot/flowpipe/releases/download/v0.1.0/flowpipe.linux.arm64.tar.gz"
      sha256 "21d0566f15b5508b77accbfd88f64be673ab01aced02086d44e07c4f985b1a0d"

      def install
        bin.install "flowpipe"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/turbot/flowpipe/releases/download/v0.1.0/flowpipe.linux.amd64.tar.gz"
      sha256 "d0517c6bf6cb4b73b69a380085e6089706276f089399271ce67084f4c4f7fc09"

      def install
        bin.install "flowpipe"
      end
    end
  end
end
