# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FlowpipeAT043 < Formula
  desc "Flowpipe is a cloud scripting engine. Automation and workflow to connect your clouds to the people, systems and data that matters."
  homepage "https://flowpipe.io/"
  version "0.4.3"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/turbot/flowpipe/releases/download/v0.4.3/flowpipe.darwin.arm64.tar.gz"
      sha256 "fc487784c429c04d86fdb0efc3e2959aaff84b21fd8e4103f606b5632a1c22a6"

      def install
        bin.install "flowpipe"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/turbot/flowpipe/releases/download/v0.4.3/flowpipe.darwin.amd64.tar.gz"
      sha256 "b2d11f34aa326151cb2823c8576625e223aab5dd673af02da60c728e986238b6"

      def install
        bin.install "flowpipe"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/turbot/flowpipe/releases/download/v0.4.3/flowpipe.linux.arm64.tar.gz"
      sha256 "670d33a3828c001f1fffa81226de6031e5fbd76749877a04ffeb1e17bfa99ebc"

      def install
        bin.install "flowpipe"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/turbot/flowpipe/releases/download/v0.4.3/flowpipe.linux.amd64.tar.gz"
      sha256 "e4e92510d0710f28c081118cc034f3fc2762e1de4f59b2c99caf0bf5d9a1877e"

      def install
        bin.install "flowpipe"
      end
    end
  end
end
