# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FlowpipeAT082 < Formula
  desc "Flowpipe is a cloud scripting engine. Automation and workflow to connect your clouds to the people, systems and data that matters."
  homepage "https://flowpipe.io/"
  version "0.8.2"

  on_macos do
    on_intel do
      url "https://github.com/turbot/flowpipe/releases/download/v0.8.2/flowpipe.darwin.amd64.tar.gz"
      sha256 "4639e2478d41619c875080657f23715dad312847d7637374623a7113b11a0668"

      def install
        bin.install "flowpipe"
      end
    end
    on_arm do
      url "https://github.com/turbot/flowpipe/releases/download/v0.8.2/flowpipe.darwin.arm64.tar.gz"
      sha256 "6cfd8195c45a643e7300d8eff53029d3276e99c5873981d41152e982262b37ab"

      def install
        bin.install "flowpipe"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/turbot/flowpipe/releases/download/v0.8.2/flowpipe.linux.amd64.tar.gz"
        sha256 "73b9b722bcbe95220b4503a454d68e3a45a471abb948bd9f4002a0efb060a0da"

        def install
          bin.install "flowpipe"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/turbot/flowpipe/releases/download/v0.8.2/flowpipe.linux.arm64.tar.gz"
        sha256 "cd5696b7e9158863b6ec8236adc0803491e40cda0508ef3f2764813ff7013706"

        def install
          bin.install "flowpipe"
        end
      end
    end
  end
end
