# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FlowpipeAT010 < Formula
  desc "Flowpipe is a cloud scripting engine. Automation and workflow to connect your clouds to the people, systems and data that matters."
  homepage "https://flowpipe.io/"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/turbot/flowpipe/releases/download/0.1.0/flowpipe.darwin.arm64.tar.gz"
      sha256 "898c18b01ae62b12e9f391cc3930bd6d530ff19bfdce6d6b18a2159d4d5da3c9"

      def install
        bin.install "flowpipe"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/turbot/flowpipe/releases/download/0.1.0/flowpipe.darwin.amd64.tar.gz"
      sha256 "cac39136d1b0daac865b392d42e264dc159fc6127759a3bb052355232b97a0f5"

      def install
        bin.install "flowpipe"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/turbot/flowpipe/releases/download/0.1.0/flowpipe.linux.arm64.tar.gz"
      sha256 "5024a243fe0a8eb1362fe9d682b6790597490504e07e0a33ce7ecda0702e5cb8"

      def install
        bin.install "flowpipe"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/turbot/flowpipe/releases/download/0.1.0/flowpipe.linux.amd64.tar.gz"
      sha256 "eb3f24d99e0a49d22af79f06979be70e2178565f844d331c4590c3a32f7d7286"

      def install
        bin.install "flowpipe"
      end
    end
  end
end
