# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FlowpipeAT070 < Formula
  desc "Flowpipe is a cloud scripting engine. Automation and workflow to connect your clouds to the people, systems and data that matters."
  homepage "https://flowpipe.io/"
  version "0.7.0"

  on_macos do
    on_intel do
      url "https://github.com/turbot/flowpipe/releases/download/v0.7.0/flowpipe.darwin.amd64.tar.gz"
      sha256 "a931337b97e3bddc50c3a6bee0bbd14b89ed046ec8a98cb00b475990ce6d3cf2"

      def install
        bin.install "flowpipe"
      end
    end
    on_arm do
      url "https://github.com/turbot/flowpipe/releases/download/v0.7.0/flowpipe.darwin.arm64.tar.gz"
      sha256 "58e21ffb9da951aaa002dd9991b6a68326f7e5a13acd40b5ac095c61b68cf455"

      def install
        bin.install "flowpipe"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/turbot/flowpipe/releases/download/v0.7.0/flowpipe.linux.amd64.tar.gz"
        sha256 "1f7e071bb5c2ab2ca81f3ee82d2a4fcc8305c40520212a0677a737ed9245d063"

        def install
          bin.install "flowpipe"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/turbot/flowpipe/releases/download/v0.7.0/flowpipe.linux.arm64.tar.gz"
        sha256 "7a31f52218885435ef899086152c4f51e0355e18875b5aa22c7afa3b2f7febbb"

        def install
          bin.install "flowpipe"
        end
      end
    end
  end
end
