# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Flowpipe < Formula
  desc "Flowpipe is a cloud scripting engine. Automation and workflow to connect your clouds to the people, systems and data that matters."
  homepage "https://flowpipe.io/"
  version "1.0.2"

  on_macos do
    on_intel do
      url "https://github.com/turbot/flowpipe/releases/download/v1.0.2/flowpipe.darwin.amd64.tar.gz"
      sha256 "0749ce0bf5501c61d632b9542d0d0d0dccf2e5db8565fcc88da4ca1737d727c0"

      def install
        bin.install "flowpipe"
      end
    end
    on_arm do
      url "https://github.com/turbot/flowpipe/releases/download/v1.0.2/flowpipe.darwin.arm64.tar.gz"
      sha256 "537c313e0041ba6ae1eccc8c439a7c7552c2fbe9dc7dbc2e614b2c7f5613af73"

      def install
        bin.install "flowpipe"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/turbot/flowpipe/releases/download/v1.0.2/flowpipe.linux.amd64.tar.gz"
        sha256 "6607f408e176441cd2ff2a580c7348c78663441a19becaad32ee9827c7320c17"

        def install
          bin.install "flowpipe"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/turbot/flowpipe/releases/download/v1.0.2/flowpipe.linux.arm64.tar.gz"
        sha256 "3305b1c4322a2fa156735b66c5f526b78dd6d602e6f92d66982ce51f7ccb865b"

        def install
          bin.install "flowpipe"
        end
      end
    end
  end
end
