# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FlowpipeAT072 < Formula
  desc "Flowpipe is a cloud scripting engine. Automation and workflow to connect your clouds to the people, systems and data that matters."
  homepage "https://flowpipe.io/"
  version "0.7.2"

  on_macos do
    on_intel do
      url "https://github.com/turbot/flowpipe/releases/download/v0.7.2/flowpipe.darwin.amd64.tar.gz"
      sha256 "72b1b942951504fb9c3ff055250f2c34a66952b98f0434a8934e949bf9c40d93"

      def install
        bin.install "flowpipe"
      end
    end
    on_arm do
      url "https://github.com/turbot/flowpipe/releases/download/v0.7.2/flowpipe.darwin.arm64.tar.gz"
      sha256 "6c86341c60db33ad1169e450ccb86bd0745b2fe299e9d8f625a15dd1be13a485"

      def install
        bin.install "flowpipe"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/turbot/flowpipe/releases/download/v0.7.2/flowpipe.linux.amd64.tar.gz"
        sha256 "04f155b774791406513d75e99b93f35fac1876414f8e24afc974717a0b92c041"

        def install
          bin.install "flowpipe"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/turbot/flowpipe/releases/download/v0.7.2/flowpipe.linux.arm64.tar.gz"
        sha256 "3113e7a8b397cd641a9db5ac081a6bb214732e2941849846b9301150691b1317"

        def install
          bin.install "flowpipe"
        end
      end
    end
  end
end
