# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FlowpipeAT020 < Formula
  desc "Flowpipe is a cloud scripting engine. Automation and workflow to connect your clouds to the people, systems and data that matters."
  homepage "https://flowpipe.io/"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/turbot/flowpipe/releases/download/v0.2.0/flowpipe.darwin.arm64.tar.gz"
      sha256 "2617f6b65f12eba58ee51d973982f1bf8229d9986e1c720d9676f3e05d43b021"

      def install
        bin.install "flowpipe"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/turbot/flowpipe/releases/download/v0.2.0/flowpipe.darwin.amd64.tar.gz"
      sha256 "4cd0cc0482809a23a1fb6dc3dfcc6fd7f91a0004a52479333a6e15eeca181298"

      def install
        bin.install "flowpipe"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/turbot/flowpipe/releases/download/v0.2.0/flowpipe.linux.arm64.tar.gz"
      sha256 "bd2ad30b1be4ae8fb208efe3c3604f8c569acf30df0f04d187d0be5263b7804e"

      def install
        bin.install "flowpipe"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/turbot/flowpipe/releases/download/v0.2.0/flowpipe.linux.amd64.tar.gz"
      sha256 "1fac55f4663569dba177f03aa5e5e0901f5aed4dd492b9f24fdedec51c44d8d2"

      def install
        bin.install "flowpipe"
      end
    end
  end
end
