# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FlowpipeAT021 < Formula
  desc "Flowpipe is a cloud scripting engine. Automation and workflow to connect your clouds to the people, systems and data that matters."
  homepage "https://flowpipe.io/"
  version "0.2.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/turbot/flowpipe/releases/download/v0.2.1/flowpipe.darwin.arm64.tar.gz"
      sha256 "42188dd67226bbd85fd4199fc7a44bacead38de5f4017ef711c9ceab8398bfbe"

      def install
        bin.install "flowpipe"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/turbot/flowpipe/releases/download/v0.2.1/flowpipe.darwin.amd64.tar.gz"
      sha256 "b8a34485954c1ade1aca0c0f2d291327cf55a65fa191ac3458faec1b12029cc4"

      def install
        bin.install "flowpipe"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/turbot/flowpipe/releases/download/v0.2.1/flowpipe.linux.arm64.tar.gz"
      sha256 "c57ef2c6b8018d6af8c57f4cdfa049c7d3df03a0fbc55590641c1007f58e9752"

      def install
        bin.install "flowpipe"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/turbot/flowpipe/releases/download/v0.2.1/flowpipe.linux.amd64.tar.gz"
      sha256 "59ffe609301f1aa9b6bacf95ff270f8530f2ea0a0ca75f9369c1218a4dfcf5cd"

      def install
        bin.install "flowpipe"
      end
    end
  end
end
