# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FlowpipeAT040 < Formula
  desc "Flowpipe is a cloud scripting engine. Automation and workflow to connect your clouds to the people, systems and data that matters."
  homepage "https://flowpipe.io/"
  version "0.4.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/turbot/flowpipe/releases/download/v0.4.0/flowpipe.darwin.arm64.tar.gz"
      sha256 "88b0687e8c01d2757bce806212058de5106afc1357a4dd7f7d1011e70e38ab00"

      def install
        bin.install "flowpipe"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/turbot/flowpipe/releases/download/v0.4.0/flowpipe.darwin.amd64.tar.gz"
      sha256 "971c061aa8dbe7283ee93de28a5e6592e318695f08f94c7a80a7183c0fd63595"

      def install
        bin.install "flowpipe"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/turbot/flowpipe/releases/download/v0.4.0/flowpipe.linux.arm64.tar.gz"
      sha256 "96ee902cf798198fa1a0b78f40863582dd8114b68281e054b78cc16cea21720c"

      def install
        bin.install "flowpipe"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/turbot/flowpipe/releases/download/v0.4.0/flowpipe.linux.amd64.tar.gz"
      sha256 "612a3cc08e186c8bfe823e972662b16129975e806d55286a4f37b53169d8ee55"

      def install
        bin.install "flowpipe"
      end
    end
  end
end
