# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FlowpipeAT122 < Formula
  desc "Flowpipe is a cloud scripting engine. Automation and workflow to connect your clouds to the people, systems and data that matters."
  homepage "https://flowpipe.io/"
  version "1.2.2"

  on_macos do
    on_intel do
      url "https://github.com/turbot/flowpipe/releases/download/v1.2.2/flowpipe.darwin.amd64.tar.gz"
      sha256 "291f1d58db215255b48066da7d2884123e25fd44742b503eb674cfbbb367f4cc"

      def install
        bin.install "flowpipe"
      end
    end
    on_arm do
      url "https://github.com/turbot/flowpipe/releases/download/v1.2.2/flowpipe.darwin.arm64.tar.gz"
      sha256 "1691ea438aabedac3e9e5a1c17e5e5fabd019468c24c0aa925808723c29d6bc7"

      def install
        bin.install "flowpipe"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/turbot/flowpipe/releases/download/v1.2.2/flowpipe.linux.amd64.tar.gz"
        sha256 "b709b08bf400d32f4612adb2efce8a6ab8c6cd5cb4fc7f268f37a9183b612562"

        def install
          bin.install "flowpipe"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/turbot/flowpipe/releases/download/v1.2.2/flowpipe.linux.arm64.tar.gz"
        sha256 "c9021574d16210f0ce0ceab1db968b34939020cdce47c90a6b4f86029a95ecdf"

        def install
          bin.install "flowpipe"
        end
      end
    end
  end
end
