# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PowerpipeAT155 < Formula
  desc "Dashboards for DevOps. Visualize cloud configurations. Assess security posture against a massive library of benchmarks. Build custom dashboards with code."
  homepage "https://powerpipe.io/"
  version "1.5.5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/turbot/powerpipe/releases/download/v1.5.5/powerpipe.darwin.amd64.tar.gz"
      sha256 "eecde325c6eae5ae3d78222e6e61635cba0692cdc9cbe5d7ccb7891228c0273c"

      def install
        bin.install "powerpipe"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/turbot/powerpipe/releases/download/v1.5.5/powerpipe.darwin.arm64.tar.gz"
      sha256 "ad5149048a37b23cfc7f6050483feaf963ca6d7944025f39914777a2099ea28e"

      def install
        bin.install "powerpipe"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/turbot/powerpipe/releases/download/v1.5.5/powerpipe.linux.amd64.tar.gz"
      sha256 "9d834c95a73790ed4a1307eac97095ff762b0b7dbe507d8676e891dacde384c6"
      def install
        bin.install "powerpipe"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/turbot/powerpipe/releases/download/v1.5.5/powerpipe.linux.arm64.tar.gz"
      sha256 "5429ba99007e87091d57842913d008a7c760ad4b5608d337d5ee7be70e21595c"
      def install
        bin.install "powerpipe"
      end
    end
  end
end
