# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PowerpipeAT010 < Formula
  desc "Dashboards for DevOps. Visualize cloud configurations. Assess security posture against a massive library of benchmarks. Build custom dashboards with code."
  homepage "https://powerpipe.io/"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/turbot/powerpipe/releases/download/v0.1.0/powerpipe.darwin.arm64.tar.gz"
      sha256 "59836abbf330d5b548b01e868abe5312ca7fa73df00b06c5c526db7ac2ec4c75"

      def install
        bin.install "powerpipe"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/turbot/powerpipe/releases/download/v0.1.0/powerpipe.darwin.amd64.tar.gz"
      sha256 "269a28d312fbd5df1b18c039b415571b4d33890435c7292f9faa1864f269a91b"

      def install
        bin.install "powerpipe"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/turbot/powerpipe/releases/download/v0.1.0/powerpipe.linux.arm64.tar.gz"
      sha256 "16b04e6aa07a2cc099f70d7ac71e11c1d91e1bfd8f5d93cdf0d6400196578973"

      def install
        bin.install "powerpipe"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/turbot/powerpipe/releases/download/v0.1.0/powerpipe.linux.amd64.tar.gz"
      sha256 "e9598d44a669c9416f48d9320685724ea64c5768f1780cc532d77391e9f2dc35"

      def install
        bin.install "powerpipe"
      end
    end
  end
end
