# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PowerpipeAT124 < Formula
  desc "Dashboards for DevOps. Visualize cloud configurations. Assess security posture against a massive library of benchmarks. Build custom dashboards with code."
  homepage "https://powerpipe.io/"
  version "1.2.4"

  on_macos do
    on_intel do
      url "https://github.com/turbot/powerpipe/releases/download/v1.2.4/powerpipe.darwin.amd64.tar.gz"
      sha256 "be2735beed90753a7ea409cb98ff723540914c068071b2495f6cb065a3397e75"

      def install
        bin.install "powerpipe"
      end
    end
    on_arm do
      url "https://github.com/turbot/powerpipe/releases/download/v1.2.4/powerpipe.darwin.arm64.tar.gz"
      sha256 "d3e5a361a2557289d314055eee4ac1bf449cc8a2fcda00bc40f5f31cb4287a57"

      def install
        bin.install "powerpipe"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/turbot/powerpipe/releases/download/v1.2.4/powerpipe.linux.amd64.tar.gz"
        sha256 "4d3ee374339e448fbd57c91b2b8d5c860c10290ce3c675bf76fbd21f969c79a9"

        def install
          bin.install "powerpipe"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/turbot/powerpipe/releases/download/v1.2.4/powerpipe.linux.arm64.tar.gz"
        sha256 "c1d0fc481bd2676e3027d02c6394356ed6aa2a81a6490c5eabfb6df055bb018d"

        def install
          bin.install "powerpipe"
        end
      end
    end
  end
end
