# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PowerpipeAT020 < Formula
  desc "Dashboards for DevOps. Visualize cloud configurations. Assess security posture against a massive library of benchmarks. Build custom dashboards with code."
  homepage "https://powerpipe.io/"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/turbot/powerpipe/releases/download/v0.2.0/powerpipe.darwin.arm64.tar.gz"
      sha256 "0e80bc9998db435e388c333c479c9dfa128eb5bba391e66a170f3525c40d7d36"

      def install
        bin.install "powerpipe"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/turbot/powerpipe/releases/download/v0.2.0/powerpipe.darwin.amd64.tar.gz"
      sha256 "5cef83f8ee63753de0b85451fa2a133b724f5c2f2a7ced90582505a89364631e"

      def install
        bin.install "powerpipe"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/turbot/powerpipe/releases/download/v0.2.0/powerpipe.linux.arm64.tar.gz"
      sha256 "7db6e23539b40409aef315254307b1eca8583a2d3f29ef43516811368a381ac9"

      def install
        bin.install "powerpipe"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/turbot/powerpipe/releases/download/v0.2.0/powerpipe.linux.amd64.tar.gz"
      sha256 "e65b4b79a7aa29438daca457bcd69d9546cea9bebf89fc14d4bbb6a9b543c35e"

      def install
        bin.install "powerpipe"
      end
    end
  end
end
