# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PowerpipeAT121 < Formula
  desc "Dashboards for DevOps. Visualize cloud configurations. Assess security posture against a massive library of benchmarks. Build custom dashboards with code."
  homepage "https://powerpipe.io/"
  version "1.2.1"

  on_macos do
    on_intel do
      url "https://github.com/turbot/powerpipe/releases/download/v1.2.1/powerpipe.darwin.amd64.tar.gz"
      sha256 "c4219fe9cd962605e10b79d9efb51323f66c1a25a55e98d9f4bf16d7b7c6a982"

      def install
        bin.install "powerpipe"
      end
    end
    on_arm do
      url "https://github.com/turbot/powerpipe/releases/download/v1.2.1/powerpipe.darwin.arm64.tar.gz"
      sha256 "6c90b5bb3eb8879a7acb0e1d2150b5f20cd8f28c6f4dbb9354361f1b77bce7c3"

      def install
        bin.install "powerpipe"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/turbot/powerpipe/releases/download/v1.2.1/powerpipe.linux.amd64.tar.gz"
        sha256 "18c8c0521ad793ae296eb76c2255257d34f2fa5868aea94c0ec16bbbe40ca5cd"

        def install
          bin.install "powerpipe"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/turbot/powerpipe/releases/download/v1.2.1/powerpipe.linux.arm64.tar.gz"
        sha256 "6a990b3055ce83aeca20ff0ec2c9d026337ee3e156a3a745a0016e4371c5f5f5"

        def install
          bin.install "powerpipe"
        end
      end
    end
  end
end
