# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PowerpipeAT012 < Formula
  desc "Dashboards for DevOps. Visualize cloud configurations. Assess security posture against a massive library of benchmarks. Build custom dashboards with code."
  homepage "https://powerpipe.io/"
  version "0.1.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/turbot/powerpipe/releases/download/v0.1.2/powerpipe.darwin.arm64.tar.gz"
      sha256 "538497c0895f60bc6bdb560a5d987821236fa4df7056628b68f43efcb062497d"

      def install
        bin.install "powerpipe"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/turbot/powerpipe/releases/download/v0.1.2/powerpipe.darwin.amd64.tar.gz"
      sha256 "40f752a89e91f1daec4c47a0d4fc4e3ee0e3e7bab260031e0d68ce817275f85c"

      def install
        bin.install "powerpipe"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/turbot/powerpipe/releases/download/v0.1.2/powerpipe.linux.arm64.tar.gz"
      sha256 "da567e98f0bb722749ea4236ee4929124165f10707a0407b92b978d6dbeef98e"

      def install
        bin.install "powerpipe"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/turbot/powerpipe/releases/download/v0.1.2/powerpipe.linux.amd64.tar.gz"
      sha256 "1c5b2bfef8210fe57b8ae7e1f327cf73cc4d0735737a06fee0588b702e7cf47e"

      def install
        bin.install "powerpipe"
      end
    end
  end
end
