# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Powerpipe < Formula
  desc "Dashboards for DevOps. Visualize cloud configurations. Assess security posture against a massive library of benchmarks. Build custom dashboards with code."
  homepage "https://powerpipe.io/"
  version "0.4.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/turbot/powerpipe/releases/download/v0.4.1/powerpipe.darwin.arm64.tar.gz"
      sha256 "0fadf41a0570eaa217e5e78fdc1f4b70fab9644521c111a0f4c9fc3c160ce2d0"

      def install
        bin.install "powerpipe"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/turbot/powerpipe/releases/download/v0.4.1/powerpipe.darwin.amd64.tar.gz"
      sha256 "52aa37c86cdc0077bb7958141bf9dba852fc2208ef54f6749178bec542a405f2"

      def install
        bin.install "powerpipe"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/turbot/powerpipe/releases/download/v0.4.1/powerpipe.linux.arm64.tar.gz"
      sha256 "99f73213761acedbe677329504d765001716d4030f19a7680e284ae4111fd451"

      def install
        bin.install "powerpipe"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/turbot/powerpipe/releases/download/v0.4.1/powerpipe.linux.amd64.tar.gz"
      sha256 "80869a390d209acd30acda0770234ed41b51e8eb236977d27dc214d67265391d"

      def install
        bin.install "powerpipe"
      end
    end
  end
end
