# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PowerpipeAT044 < Formula
  desc "Dashboards for DevOps. Visualize cloud configurations. Assess security posture against a massive library of benchmarks. Build custom dashboards with code."
  homepage "https://powerpipe.io/"
  version "0.4.4"

  on_macos do
    on_intel do
      url "https://github.com/turbot/powerpipe/releases/download/v0.4.4/powerpipe.darwin.amd64.tar.gz"
      sha256 "3635c953a7592e54831ddb666a8f0976095895ab5261ae3abf69a79a8ada49bd"

      def install
        bin.install "powerpipe"
      end
    end
    on_arm do
      url "https://github.com/turbot/powerpipe/releases/download/v0.4.4/powerpipe.darwin.arm64.tar.gz"
      sha256 "69050e26799a43c9fca33767d55387a3398f6a47b16706828392a580ce7f7c4a"

      def install
        bin.install "powerpipe"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/turbot/powerpipe/releases/download/v0.4.4/powerpipe.linux.amd64.tar.gz"
        sha256 "3cc420bdd015b11b7016cb39d08a4d53375e677e41a5898afaa676573e7e272c"

        def install
          bin.install "powerpipe"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/turbot/powerpipe/releases/download/v0.4.4/powerpipe.linux.arm64.tar.gz"
        sha256 "5e1974db84a068843fac340da34298162bb299cf2d4c9e219db700ec7d62d4b8"

        def install
          bin.install "powerpipe"
        end
      end
    end
  end
end
