# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PowerpipeAT031 < Formula
  desc "Dashboards for DevOps. Visualize cloud configurations. Assess security posture against a massive library of benchmarks. Build custom dashboards with code."
  homepage "https://powerpipe.io/"
  version "0.3.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/turbot/powerpipe/releases/download/v0.3.1/powerpipe.darwin.arm64.tar.gz"
      sha256 "b508f5f3541f06415b7b29cbafa409246f86a6dfc06ae11553d4c27f47fc9059"

      def install
        bin.install "powerpipe"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/turbot/powerpipe/releases/download/v0.3.1/powerpipe.darwin.amd64.tar.gz"
      sha256 "4e95db9e259d0c8846ab8bc4c08244a0e89da6000e79def5189344a367570d73"

      def install
        bin.install "powerpipe"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/turbot/powerpipe/releases/download/v0.3.1/powerpipe.linux.arm64.tar.gz"
      sha256 "5c70abce459d109e1b79d6abbed1f052554493da5249e190348740aeddecb19f"

      def install
        bin.install "powerpipe"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/turbot/powerpipe/releases/download/v0.3.1/powerpipe.linux.amd64.tar.gz"
      sha256 "f7945a01a8b262b087fe693e0adece99b60e68d8a341f5615e249d7ecf86eb71"

      def install
        bin.install "powerpipe"
      end
    end
  end
end
