# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Powerpipe < Formula
  desc "Dashboards for DevOps. Visualize cloud configurations. Assess security posture against a massive library of benchmarks. Build custom dashboards with code."
  homepage "https://powerpipe.io/"
  version "1.2.8"

  on_macos do
    on_intel do
      url "https://github.com/turbot/powerpipe/releases/download/v1.2.8/powerpipe.darwin.amd64.tar.gz"
      sha256 "8ff26d16b6b124f2d4d2a22e4298b3321959a3f81f69a7a52693b89e6a554cde"

      def install
        bin.install "powerpipe"
      end
    end
    on_arm do
      url "https://github.com/turbot/powerpipe/releases/download/v1.2.8/powerpipe.darwin.arm64.tar.gz"
      sha256 "ba2eb754c38d42012eac9f7e7472c4fcb91ad88430fc197f262b4b73acba0b80"

      def install
        bin.install "powerpipe"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/turbot/powerpipe/releases/download/v1.2.8/powerpipe.linux.amd64.tar.gz"
        sha256 "8e28b179e82b075ea7b52dc8c2bd26182dab9603051270665e1f01932e819db3"

        def install
          bin.install "powerpipe"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/turbot/powerpipe/releases/download/v1.2.8/powerpipe.linux.arm64.tar.gz"
        sha256 "73537a48d74c627137fb37692f82bb8153ab959004677ec43ecd95878516111a"

        def install
          bin.install "powerpipe"
        end
      end
    end
  end
end
