# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Powerpipe < Formula
  desc "Dashboards for DevOps. Visualize cloud configurations. Assess security posture against a massive library of benchmarks. Build custom dashboards with code."
  homepage "https://powerpipe.io/"
  version "1.2.7"

  on_macos do
    on_intel do
      url "https://github.com/turbot/powerpipe/releases/download/v1.2.7/powerpipe.darwin.amd64.tar.gz"
      sha256 "e328fa2b3a83020f32af02f935a17149fe5e9f3ec02429c0aa744182122d99c7"

      def install
        bin.install "powerpipe"
      end
    end
    on_arm do
      url "https://github.com/turbot/powerpipe/releases/download/v1.2.7/powerpipe.darwin.arm64.tar.gz"
      sha256 "43f13168ed3dad01cfd4237008d88e44ece5ea6875c7cf2d92f14bbdbfa6b67f"

      def install
        bin.install "powerpipe"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/turbot/powerpipe/releases/download/v1.2.7/powerpipe.linux.amd64.tar.gz"
        sha256 "5bfb7286147c353a72b13ca603c9b88597e1a7bc7f4134e939f021f4e9413e0d"

        def install
          bin.install "powerpipe"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/turbot/powerpipe/releases/download/v1.2.7/powerpipe.linux.arm64.tar.gz"
        sha256 "0f085b9aabd6530e44755eddf3d5ca8b32e9e23c921df9947317cb7727aa2787"

        def install
          bin.install "powerpipe"
        end
      end
    end
  end
end
