# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SteampipeAT0172 < Formula
  desc "Steampipe exposes APIs and services as a high-performance relational database, giving you the ability to write SQL-based queries to explore, assess and report on dynamic data."
  homepage "https://steampipe.io/"
  version "0.17.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/turbot/steampipe/releases/download/v0.17.2/steampipe_darwin_amd64.zip"
      sha256 "d858d9a2f8c324485ba85f7d7b8d7390fc8c16f6f0eb839e4339a3bb7949cb6e"

      def install
        bin.install "steampipe"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/turbot/steampipe/releases/download/v0.17.2/steampipe_darwin_arm64.zip"
      sha256 "29bd7e35e76d87026434df42654b36e64122d56a8d628bfbcd133ad9bc73ead6"

      def install
        bin.install "steampipe"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/turbot/steampipe/releases/download/v0.17.2/steampipe_linux_arm64.tar.gz"
      sha256 "9e2209d3e6e376e3ccb9e347fca198d63be9876fe1b23dde33f8da01d43fa848"

      def install
        bin.install "steampipe"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/turbot/steampipe/releases/download/v0.17.2/steampipe_linux_amd64.tar.gz"
      sha256 "771c843521033551035755e58ba993cd34eb3f459d7558e4749705ca4a95af6c"

      def install
        bin.install "steampipe"
      end
    end
  end
end
