# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SteampipeAT0209 < Formula
  desc "Steampipe exposes APIs and services as a high-performance relational database, giving you the ability to write SQL-based queries to explore, assess and report on dynamic data."
  homepage "https://steampipe.io/"
  version "0.20.9"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/turbot/steampipe/releases/download/v0.20.9/steampipe_darwin_arm64.zip"
      sha256 "0621967324dba60874105c8c9c6f1eae2b2dd5da276a615c006db69a98081c65"

      def install
        bin.install "steampipe"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/turbot/steampipe/releases/download/v0.20.9/steampipe_darwin_amd64.zip"
      sha256 "9b1f8e84b1bfa5ab6a1d99c4d037c3412e13461c014ea6e64d7a11167671cf1a"

      def install
        bin.install "steampipe"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/turbot/steampipe/releases/download/v0.20.9/steampipe_linux_arm64.tar.gz"
      sha256 "07fff24201ead221e40c2eddade21f298c3c4e288333f9eca915a6d9c3cc3ebc"

      def install
        bin.install "steampipe"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/turbot/steampipe/releases/download/v0.20.9/steampipe_linux_amd64.tar.gz"
      sha256 "8a148a55b8252239784b4c089e07f5c7b2863d9421949cc0937e8895b87c820d"

      def install
        bin.install "steampipe"
      end
    end
  end
end
