# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SteampipeAT120 < Formula
  desc "Steampipe exposes APIs and services as a high-performance relational database, giving you the ability to write SQL-based queries to explore, assess and report on dynamic data."
  homepage "https://steampipe.io/"
  version "1.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/turbot/steampipe/releases/download/v1.2.0/steampipe_darwin_amd64.zip"
      sha256 "ff772b0b38f26449aaacc55dbe34d2e1b4147b6d9ff64a7fa5df7f8bd2de5b0d"

      def install
        bin.install "steampipe"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/turbot/steampipe/releases/download/v1.2.0/steampipe_darwin_arm64.zip"
      sha256 "d0fa5b862f27ae9b02ed2ed67306f593f31f728eb11268f97bd670342f0911d7"

      def install
        bin.install "steampipe"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/turbot/steampipe/releases/download/v1.2.0/steampipe_linux_amd64.tar.gz"
      sha256 "1c3a20fa0450a58bf8677c5249f6e98ae6a60c5f9e1e1957e69886a152a8ed06"
      def install
        bin.install "steampipe"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/turbot/steampipe/releases/download/v1.2.0/steampipe_linux_arm64.tar.gz"
      sha256 "a354d5fd527cc629ed0c5a8d0be1896aff1e59e38ee5e85e09653d6abd824dba"
      def install
        bin.install "steampipe"
      end
    end
  end
end
