# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SteampipeAT234 < Formula
  desc "Steampipe exposes APIs and services as a high-performance relational database, giving you the ability to write SQL-based queries to explore, assess and report on dynamic data."
  homepage "https://steampipe.io/"
  version "2.3.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/turbot/steampipe/releases/download/v2.3.4/steampipe_darwin_amd64.zip"
      sha256 "0fce5d824ff3851653744af2a648e06b0cae69fd69de176fd7b3863d31ff5084"

      def install
        bin.install "steampipe"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/turbot/steampipe/releases/download/v2.3.4/steampipe_darwin_arm64.zip"
      sha256 "e862ce6517f9e81380b3490d609993332e9bbd93b70ca74f739150db0aaa3e67"

      def install
        bin.install "steampipe"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/turbot/steampipe/releases/download/v2.3.4/steampipe_linux_amd64.tar.gz"
      sha256 "633129c9ccb931965f63bf742961e1c575938dab77834e34539ca807c6361e22"
      def install
        bin.install "steampipe"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/turbot/steampipe/releases/download/v2.3.4/steampipe_linux_arm64.tar.gz"
      sha256 "0e11aae9ff82637b3bbca9a937a4db9dcb97f43975195862bc5cdc3d8a65e589"
      def install
        bin.install "steampipe"
      end
    end
  end
end
