# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SteampipeAT10 < Formula
  desc "Steampipe exposes APIs and services as a high-performance relational database, giving you the ability to write SQL-based queries to explore, assess and report on dynamic data."
  homepage "https://steampipe.io/"
  version "1.0.0"

  on_macos do
    on_intel do
      url "https://github.com/turbot/steampipe/releases/download/v1.0.0/steampipe_darwin_amd64.zip"
      sha256 "e05082dc2eca6b1ddbd451aca2d77755cfd46eac1ccefd5986f83b6dc9dd41c0"

      def install
        bin.install "steampipe"
      end
    end
    on_arm do
      url "https://github.com/turbot/steampipe/releases/download/v1.0.0/steampipe_darwin_arm64.zip"
      sha256 "b27354ad1766ef904512a26702d0b588034a89b41db124c0aff9a0941bfe924b"

      def install
        bin.install "steampipe"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/turbot/steampipe/releases/download/v1.0.0/steampipe_linux_amd64.tar.gz"
        sha256 "0faef51472dfc2d3e8eea9ad5d728995f867da7664c99947d523258b74e10d7f"

        def install
          bin.install "steampipe"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/turbot/steampipe/releases/download/v1.0.0/steampipe_linux_arm64.tar.gz"
        sha256 "6fdc06f0c717c076ad22301a342550223ef1e4f74059a9f869bc7412f39cf606"

        def install
          bin.install "steampipe"
        end
      end
    end
  end
end
