# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SteampipeAT210 < Formula
  desc "Steampipe exposes APIs and services as a high-performance relational database, giving you the ability to write SQL-based queries to explore, assess and report on dynamic data."
  homepage "https://steampipe.io/"
  version "2.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/turbot/steampipe/releases/download/v2.1.0/steampipe_darwin_amd64.zip"
      sha256 "d0ed365a9cb1e22b31ce760d9d484832a5907995a26bf24ed814b244dc3924df"

      def install
        bin.install "steampipe"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/turbot/steampipe/releases/download/v2.1.0/steampipe_darwin_arm64.zip"
      sha256 "97f63dcf7e827a5977262659d4c6ce119a838f3d8e2c70ffb5cecad772c3a721"

      def install
        bin.install "steampipe"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/turbot/steampipe/releases/download/v2.1.0/steampipe_linux_amd64.tar.gz"
      sha256 "17c4129e2d38012d94c093a17920284b0e1fd48ef80ffeab3116fca7d0e9e9ba"
      def install
        bin.install "steampipe"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/turbot/steampipe/releases/download/v2.1.0/steampipe_linux_arm64.tar.gz"
      sha256 "cd43b4ce63b066a7eb570ada95d4526aeeb50714ad6c32b2ae6d29678a0af4a5"
      def install
        bin.install "steampipe"
      end
    end
  end
end
