# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SteampipeAT0172 < Formula
  desc "Steampipe exposes APIs and services as a high-performance relational database, giving you the ability to write SQL-based queries to explore, assess and report on dynamic data."
  homepage "https://steampipe.io/"
  version "0.17.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/turbot/steampipe/releases/download/v0.17.2/steampipe_darwin_amd64.zip"
      sha256 "f6b96b1e20d69d197c56f4bdb88e6d915971bff7036c621f086462be6abee7f7"

      def install
        bin.install "steampipe"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/turbot/steampipe/releases/download/v0.17.2/steampipe_darwin_arm64.zip"
      sha256 "31304d791b66fb8b37da13d188c9a2d88ad85644d75839d591ad412c4e8d6109"

      def install
        bin.install "steampipe"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/turbot/steampipe/releases/download/v0.17.2/steampipe_linux_arm64.tar.gz"
      sha256 "2b45e0edb8f104950fe8befd4286703834c409cb74f5964257757f62534f2d4d"

      def install
        bin.install "steampipe"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/turbot/steampipe/releases/download/v0.17.2/steampipe_linux_amd64.tar.gz"
      sha256 "5199f69a4e2ed5e8e9f210a41382db9bb1a0dfdb0eb84864ae15a2f816a9666f"

      def install
        bin.install "steampipe"
      end
    end
  end
end
