# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SteampipeAT0214 < Formula
  desc "Steampipe exposes APIs and services as a high-performance relational database, giving you the ability to write SQL-based queries to explore, assess and report on dynamic data."
  homepage "https://steampipe.io/"
  version "0.21.4"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/turbot/steampipe/releases/download/v0.21.4/steampipe_darwin_arm64.zip"
      sha256 "a28f7098f757215148c140c37d22349686b77fbe065e2c365bf5fae12dbd86e0"

      def install
        bin.install "steampipe"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/turbot/steampipe/releases/download/v0.21.4/steampipe_darwin_amd64.zip"
      sha256 "3fe268d9878c9e88a61057a6cf9bda0dcc0da5833299359427bc344b95f89f28"

      def install
        bin.install "steampipe"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/turbot/steampipe/releases/download/v0.21.4/steampipe_linux_arm64.tar.gz"
      sha256 "179af6df4ab1eb69a5c845d371d25221e0089a7234cd2731a1dd2d34ba149d87"

      def install
        bin.install "steampipe"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/turbot/steampipe/releases/download/v0.21.4/steampipe_linux_amd64.tar.gz"
      sha256 "a098704a9c7f491f0953f955375ad6bc9d2cc776f57a5d73db05d3752e2307c8"

      def install
        bin.install "steampipe"
      end
    end
  end
end
