# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Steampipe < Formula
  desc "Steampipe exposes APIs and services as a high-performance relational database, giving you the ability to write SQL-based queries to explore, assess and report on dynamic data."
  homepage "https://steampipe.io/"
  version "0.15.10"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/turbot/steampipe/releases/download/v0.15.10/steampipe_darwin_arm64.zip"
      sha256 "fd6ba0c2f6c49fe962328cca364ca6a21a43b0b909cc68e2fa8566f785e2b035"

      def install
        bin.install "steampipe"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/turbot/steampipe/releases/download/v0.15.10/steampipe_darwin_amd64.zip"
      sha256 "b353389a52e7a0faedc7a564b9bb0a8670bf347d67191171d514e6e8d087810d"

      def install
        bin.install "steampipe"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/turbot/steampipe/releases/download/v0.15.10/steampipe_linux_arm64.tar.gz"
      sha256 "13078901bf769075464658dd298702f78244f44ff141f75acfabe616d5697eb5"

      def install
        bin.install "steampipe"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/turbot/steampipe/releases/download/v0.15.10/steampipe_linux_amd64.tar.gz"
      sha256 "42153a159fba9a952b3a563fc554281d079e9599d24ba257f0701f6c6d5e34b8"

      def install
        bin.install "steampipe"
      end
    end
  end
end
