# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Steampipe < Formula
  desc "Steampipe exposes APIs and services as a high-performance relational database, giving you the ability to write SQL-based queries to explore, assess and report on dynamic data."
  homepage "https://steampipe.io/"
  version "2.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/turbot/steampipe/releases/download/v2.0.1/steampipe_darwin_amd64.zip"
      sha256 "9b73c673f7f1e93cb56972461666c0e404a51b486ec115dc3646980a01556a96"

      def install
        bin.install "steampipe"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/turbot/steampipe/releases/download/v2.0.1/steampipe_darwin_arm64.zip"
      sha256 "0adebf67e0c94574eaf83d3674008fdef91ad4b365710c195e1f620a7c16b963"

      def install
        bin.install "steampipe"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/turbot/steampipe/releases/download/v2.0.1/steampipe_linux_amd64.tar.gz"
      sha256 "d4abd4f528666002fce143feae5530e2a0879db6ab92403399e5dde032b12e1f"
      def install
        bin.install "steampipe"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/turbot/steampipe/releases/download/v2.0.1/steampipe_linux_arm64.tar.gz"
      sha256 "f5d913e2f6ee07fbad9cdab811fe70acfa90966e16598426f34b867f6359ba37"
      def install
        bin.install "steampipe"
      end
    end
  end
end
