# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SteampipeAT0172 < Formula
  desc "Steampipe exposes APIs and services as a high-performance relational database, giving you the ability to write SQL-based queries to explore, assess and report on dynamic data."
  homepage "https://steampipe.io/"
  version "0.17.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/turbot/steampipe/releases/download/v0.17.2/steampipe_darwin_amd64.zip"
      sha256 "f8a3f80fc0781a61f9ae210142708aa38fa6fe5baed42fca0d2c484c46bcea49"

      def install
        bin.install "steampipe"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/turbot/steampipe/releases/download/v0.17.2/steampipe_darwin_arm64.zip"
      sha256 "98f365072f65d9cc486aa7e15c6c72d047dbf5fbe6448b6249a427423f81fba5"

      def install
        bin.install "steampipe"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/turbot/steampipe/releases/download/v0.17.2/steampipe_linux_amd64.tar.gz"
      sha256 "0239f86cdd3dab1ebce9e33cceba8eed9e9851aab39caa568eeb4c6fca264e75"

      def install
        bin.install "steampipe"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/turbot/steampipe/releases/download/v0.17.2/steampipe_linux_arm64.tar.gz"
      sha256 "99a58d2002e065158b288944229cff42efc67c5e47ace01c92b26e147342b231"

      def install
        bin.install "steampipe"
      end
    end
  end
end
