# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SteampipeAT0222 < Formula
  desc "Steampipe exposes APIs and services as a high-performance relational database, giving you the ability to write SQL-based queries to explore, assess and report on dynamic data."
  homepage "https://steampipe.io/"
  version "0.22.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/turbot/steampipe/releases/download/v0.22.2/steampipe_darwin_amd64.zip"
      sha256 "60bbe12e2e051f15771adeee013e05d7e67821dc334292fcfd3e7c4ef3a860bd"

      def install
        bin.install "steampipe"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/turbot/steampipe/releases/download/v0.22.2/steampipe_darwin_arm64.zip"
      sha256 "737adad61cd9d3021c69a5ff9234b71fc4582ab2570eb5ff87160e0a503c3109"

      def install
        bin.install "steampipe"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/turbot/steampipe/releases/download/v0.22.2/steampipe_linux_amd64.tar.gz"
      sha256 "c1a040514297a022b5311deb6de2b323820a448b0d3a193fa07a20dbe14b062f"

      def install
        bin.install "steampipe"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/turbot/steampipe/releases/download/v0.22.2/steampipe_linux_arm64.tar.gz"
      sha256 "a8055cb7cf11b4a6bf9979e61a0aca4164610409fdd7143c9dfeb5ae09a9f15f"

      def install
        bin.install "steampipe"
      end
    end
  end
end
