# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Steampipe < Formula
  desc "Steampipe exposes APIs and services as a high-performance relational database, giving you the ability to write SQL-based queries to explore, assess and report on dynamic data."
  homepage "https://steampipe.io/"
  version "0.15.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/turbot/steampipe/releases/download/v0.15.1/steampipe_darwin_arm64.zip"
      sha256 "88ec549187a5a712de00ad20afff8344f3f616537d91a3e97257a7eb8f20939c"

      def install
        bin.install "steampipe"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/turbot/steampipe/releases/download/v0.15.1/steampipe_darwin_amd64.zip"
      sha256 "f8d89527bca567777ac51f9cb1c34ab5ad70ee98e145e38acfccc1246217d37d"

      def install
        bin.install "steampipe"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/turbot/steampipe/releases/download/v0.15.1/steampipe_linux_amd64.tar.gz"
      sha256 "70be70db9010f33b38620267110aaa79c5b0b08634785e702c249dd7997a458f"

      def install
        bin.install "steampipe"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/turbot/steampipe/releases/download/v0.15.1/steampipe_linux_arm64.tar.gz"
      sha256 "3c1a3639335d1e8196e7b08706eceeac8e4522a9cc97b3c0dfa16a923e5402ec"

      def install
        bin.install "steampipe"
      end
    end
  end
end
