# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SteampipeAT0235 < Formula
  desc "Steampipe exposes APIs and services as a high-performance relational database, giving you the ability to write SQL-based queries to explore, assess and report on dynamic data."
  homepage "https://steampipe.io/"
  version "0.23.5"

  on_macos do
    on_intel do
      url "https://github.com/turbot/steampipe/releases/download/v0.23.5/steampipe_darwin_amd64.zip"
      sha256 "8eec8f0c872f2043cb30a10f345f2b6832f0812e5b9235a597a1c13f7ba2a62a"

      def install
        bin.install "steampipe"
      end
    end
    on_arm do
      url "https://github.com/turbot/steampipe/releases/download/v0.23.5/steampipe_darwin_arm64.zip"
      sha256 "6767b05b509b067301836bb33909a522d18a27e10e026e166bcba247ab80d027"

      def install
        bin.install "steampipe"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/turbot/steampipe/releases/download/v0.23.5/steampipe_linux_amd64.tar.gz"
        sha256 "13f5ea2dee19641e1e043a447c705e0c79582707853731194b067c17f72c5f0e"

        def install
          bin.install "steampipe"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/turbot/steampipe/releases/download/v0.23.5/steampipe_linux_arm64.tar.gz"
        sha256 "e64cb4f7f4e6b56f0fe7b49b99d45e717f15b3845ce64ed61c2e5c34460227d6"

        def install
          bin.install "steampipe"
        end
      end
    end
  end
end
