# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SteampipeAT101 < Formula
  desc "Steampipe exposes APIs and services as a high-performance relational database, giving you the ability to write SQL-based queries to explore, assess and report on dynamic data."
  homepage "https://steampipe.io/"
  version "1.0.1"

  on_macos do
    on_intel do
      url "https://github.com/turbot/steampipe/releases/download/v1.0.1/steampipe_darwin_amd64.zip"
      sha256 "01ac8d5e478d62b7d2700d5e31d5564371a1852619083302d86e081015ae6f32"

      def install
        bin.install "steampipe"
      end
    end
    on_arm do
      url "https://github.com/turbot/steampipe/releases/download/v1.0.1/steampipe_darwin_arm64.zip"
      sha256 "306fea35942d400468f867fd30bdcdd67689dd3434b05985af3303f5978ea30e"

      def install
        bin.install "steampipe"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/turbot/steampipe/releases/download/v1.0.1/steampipe_linux_amd64.tar.gz"
        sha256 "748e30deb4cbae6fb2ddc24dc38fae95b572182c2fc68bad0c43a027d827a596"

        def install
          bin.install "steampipe"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/turbot/steampipe/releases/download/v1.0.1/steampipe_linux_arm64.tar.gz"
        sha256 "e178e6dca1e8c8d59f20c951eac45e1287520336a91437d7c4ddb66c50f0b23b"

        def install
          bin.install "steampipe"
        end
      end
    end
  end
end
