# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SteampipeAT0240 < Formula
  desc "Steampipe exposes APIs and services as a high-performance relational database, giving you the ability to write SQL-based queries to explore, assess and report on dynamic data."
  homepage "https://steampipe.io/"
  version "0.24.0"

  on_macos do
    on_intel do
      url "https://github.com/turbot/steampipe/releases/download/v0.24.0/steampipe_darwin_amd64.zip"
      sha256 "cdc6a0dea1866754bfc5ba933e0c6050a5ac92d533fb37a2766ac895c559fef1"

      def install
        bin.install "steampipe"
      end
    end
    on_arm do
      url "https://github.com/turbot/steampipe/releases/download/v0.24.0/steampipe_darwin_arm64.zip"
      sha256 "8e4cc1b85e87ee38af0e2b6aa7eab0bd9bbcb976f10d5df287de8b2d9a25a240"

      def install
        bin.install "steampipe"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/turbot/steampipe/releases/download/v0.24.0/steampipe_linux_amd64.tar.gz"
        sha256 "7e8b11a90cd4247d3389da6c8cee25d7561b53c14d20f65384332c0001793b6c"

        def install
          bin.install "steampipe"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/turbot/steampipe/releases/download/v0.24.0/steampipe_linux_arm64.tar.gz"
        sha256 "24c7f0fb521c15c9ac5f6c3563f81a26255ad577ee0cda392f4fb44dd89b4a4d"

        def install
          bin.install "steampipe"
        end
      end
    end
  end
end
