# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TailpipeAT060 < Formula
  desc "Open source SIEM for instant log insights, powered by DuckDB. Analyze millions of events in seconds, right from your terminal."
  homepage "https://tailpipe.io/"
  version "0.6.0"

  on_macos do
    on_intel do
      url "https://github.com/turbot/tailpipe/releases/download/v0.6.0/tailpipe.darwin.amd64.tar.gz"
      sha256 "1900b63c2576b73d9929a9fa6b62c0fdf93a7df8b4ba5c0b7e734495da741a3e"

      def install
        bin.install "tailpipe"
      end
    end
    on_arm do
      url "https://github.com/turbot/tailpipe/releases/download/v0.6.0/tailpipe.darwin.arm64.tar.gz"
      sha256 "f434f8775aff1c0d7952903eeb484d83050b6a9e07db14f18da1b7d2c69739b9"

      def install
        bin.install "tailpipe"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/turbot/tailpipe/releases/download/v0.6.0/tailpipe.linux.amd64.tar.gz"
        sha256 "25ca46f680f01e58e8d5fe45371f6799d7990a44eb31373ce2b8f3984294cdc7"

        def install
          bin.install "tailpipe"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/turbot/tailpipe/releases/download/v0.6.0/tailpipe.linux.arm64.tar.gz"
        sha256 "637593129f97793eaca854284f4346fab5dffcb2b6c4e9ec795d701ce1861724"

        def install
          bin.install "tailpipe"
        end
      end
    end
  end
end
