# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tailpipe < Formula
  desc "Open source SIEM for instant log insights, powered by DuckDB. Analyze millions of events in seconds, right from your terminal."
  homepage "https://tailpipe.io/"
  version "0.4.0"

  on_macos do
    on_intel do
      url "https://github.com/turbot/tailpipe/releases/download/v0.4.0/tailpipe.darwin.amd64.tar.gz"
      sha256 "6a229b40924b30cc0ddfc89dc5f8137c35a8cd6477ab0d2867120243b39eac78"

      def install
        bin.install "tailpipe"
      end
    end
    on_arm do
      url "https://github.com/turbot/tailpipe/releases/download/v0.4.0/tailpipe.darwin.arm64.tar.gz"
      sha256 "7f371c1961843015442648a8109b791aa8d855785110b70f02e2b8f3f5b32bef"

      def install
        bin.install "tailpipe"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/turbot/tailpipe/releases/download/v0.4.0/tailpipe.linux.amd64.tar.gz"
        sha256 "12a7d66955a512b57bda60a5b4ccf620b2b299e2b338096483c326c75d8b82e8"

        def install
          bin.install "tailpipe"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/turbot/tailpipe/releases/download/v0.4.0/tailpipe.linux.arm64.tar.gz"
        sha256 "24bc3757b421ed9e8124c3b541c2aebc1a5bb7f7c2e2432fd852608f160ad998"

        def install
          bin.install "tailpipe"
        end
      end
    end
  end
end
