# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TailpipeAT012 < Formula
  desc "Open source SIEM for instant log insights, powered by DuckDB. Analyze millions of events in seconds, right from your terminal."
  homepage "https://tailpipe.io/"
  version "0.1.2"

  on_macos do
    on_intel do
      url "https://github.com/turbot/tailpipe/releases/download/v0.1.2/tailpipe.darwin.amd64.tar.gz"
      sha256 "0365ce34b44b7708a60664b69202140ad6fa22ef62acbc9bc8846177e636fc36"

      def install
        bin.install "tailpipe"
      end
    end
    on_arm do
      url "https://github.com/turbot/tailpipe/releases/download/v0.1.2/tailpipe.darwin.arm64.tar.gz"
      sha256 "771cf014a3afb111933e819fd81431985b4e0dfb84b838301590cb482de0f9ae"

      def install
        bin.install "tailpipe"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/turbot/tailpipe/releases/download/v0.1.2/tailpipe.linux.amd64.tar.gz"
        sha256 "0a8d0d3608f8e5a7e30e41495093d396df4eceb184de538c2d6d770eaefd407d"

        def install
          bin.install "tailpipe"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/turbot/tailpipe/releases/download/v0.1.2/tailpipe.linux.arm64.tar.gz"
        sha256 "cf057afff453f738c75aed443cb5afe4716221a83246b3d64ddf6a168fe6eb8f"

        def install
          bin.install "tailpipe"
        end
      end
    end
  end
end
