# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TailpipeAT020 < Formula
  desc "Open source SIEM for instant log insights, powered by DuckDB. Analyze millions of events in seconds, right from your terminal."
  homepage "https://tailpipe.io/"
  version "0.2.0"

  on_macos do
    on_intel do
      url "https://github.com/turbot/tailpipe/releases/download/v0.2.0/tailpipe.darwin.amd64.tar.gz"
      sha256 "d36d2243d501d3f5adb22ac9623f9255411a5b0b3c8020c0cee4f8dccd2b8732"

      def install
        bin.install "tailpipe"
      end
    end
    on_arm do
      url "https://github.com/turbot/tailpipe/releases/download/v0.2.0/tailpipe.darwin.arm64.tar.gz"
      sha256 "321664287d5068a7f9165993aa9e806abe5b85121543f1bcdf668cdc108546b8"

      def install
        bin.install "tailpipe"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/turbot/tailpipe/releases/download/v0.2.0/tailpipe.linux.amd64.tar.gz"
        sha256 "fcde25646dc266591eace8369502ed4dd7a31933d0192dc91eab246f6bae4e35"

        def install
          bin.install "tailpipe"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/turbot/tailpipe/releases/download/v0.2.0/tailpipe.linux.arm64.tar.gz"
        sha256 "0a1cf11b6d061953d60d8164ff418bc9f0741383090c382a06db96748692aba7"

        def install
          bin.install "tailpipe"
        end
      end
    end
  end
end
