# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tailpipe < Formula
  desc "Open source SIEM for instant log insights, powered by DuckDB. Analyze millions of events in seconds, right from your terminal."
  homepage "https://tailpipe.io/"
  version "0.3.0"

  on_macos do
    on_intel do
      url "https://github.com/turbot/tailpipe/releases/download/v0.3.0/tailpipe.darwin.amd64.tar.gz"
      sha256 "426a43eee79daa6e4399e0b95b97368a2443fdcc7cde6afbeb8827be59898efb"

      def install
        bin.install "tailpipe"
      end
    end
    on_arm do
      url "https://github.com/turbot/tailpipe/releases/download/v0.3.0/tailpipe.darwin.arm64.tar.gz"
      sha256 "11547fb1f29934bf6a49cfcb1e481b757ccdf0bfe043f18cb189a9b5af09fd18"

      def install
        bin.install "tailpipe"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/turbot/tailpipe/releases/download/v0.3.0/tailpipe.linux.amd64.tar.gz"
        sha256 "ce458d75cad290886d2d98411034d9bd7eaa4eed440fc342c31dab2fb3d93b0c"

        def install
          bin.install "tailpipe"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/turbot/tailpipe/releases/download/v0.3.0/tailpipe.linux.arm64.tar.gz"
        sha256 "a31c95b44fdfbe526455b5ff21b7dfeef46f97879b309e4c9c232e6392372770"

        def install
          bin.install "tailpipe"
        end
      end
    end
  end
end
