# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TailpipeAT041 < Formula
  desc "Open source SIEM for instant log insights, powered by DuckDB. Analyze millions of events in seconds, right from your terminal."
  homepage "https://tailpipe.io/"
  version "0.4.1"

  on_macos do
    on_intel do
      url "https://github.com/turbot/tailpipe/releases/download/v0.4.1/tailpipe.darwin.amd64.tar.gz"
      sha256 "7967504f99f1a8bb4548f026ba93260c434d3ff38cc7eace0d58a734306ff72e"

      def install
        bin.install "tailpipe"
      end
    end
    on_arm do
      url "https://github.com/turbot/tailpipe/releases/download/v0.4.1/tailpipe.darwin.arm64.tar.gz"
      sha256 "70a63272cb3477bba69a223e4b4eb4f87f0abd566d74c81619c589cb950f4b86"

      def install
        bin.install "tailpipe"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/turbot/tailpipe/releases/download/v0.4.1/tailpipe.linux.amd64.tar.gz"
        sha256 "9912ae23ef032851236ff7cbc9702d825ffc002824833adb3c222cd76655c347"

        def install
          bin.install "tailpipe"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/turbot/tailpipe/releases/download/v0.4.1/tailpipe.linux.arm64.tar.gz"
        sha256 "99a59ca1c8deb99f8c589c233e74f0c4b49250e8559887c255cbed6739d2cbe5"

        def install
          bin.install "tailpipe"
        end
      end
    end
  end
end
